In [1]:
import plotly.express as px
import pandas as pd
import numpy as np
import pickle
import os

In [2]:
with open('dict_sofipos_sector.pkl', 'rb') as archivo:
    dict_sofipos = pickle.load(archivo)

In [7]:
df_indf_original = dict_sofipos['original']['Ind_financieros']
df_indf_fintech = dict_sofipos['fintech']['Ind_financieros']

In [9]:
sele_sofipos = ['Total SOFIPOS', 'Fintech', 'Fincomún']

In [12]:
df_indf_fintech_s = df_indf_fintech[df_indf_fintech['sofipo'].isin(sele_sofipos)]
df_indf_fintech_s['periodo'] = pd.to_datetime(df_indf_fintech_s['periodo'], format='%Y-%m')

In [13]:
fecha_max = df_indf_fintech_s['periodo'].max()
fecha_limite = fecha_max - pd.DateOffset(months=6)

In [25]:
df_indf_fintech_6m = df_indf_fintech_s[df_indf_fintech_s['periodo'] > fecha_limite].reset_index(drop = True)
df_indf_fintech_6m['periodo'] = df_indf_fintech_6m['periodo'].dt.strftime('%Y-%m')

In [18]:
df_indf_fintech_6m

,periodo,Capital contable / Activo,EPRC / Cartera de crédito,GAP / Activo,ICOR cartera de crédito,IMOR cartera de crédito,IMORA cartera de crédito,Liquidez,MIN,ROA,...,IMOR cartera de crédito_pct_YoY,IMORA cartera de crédito_pct_YoY,Liquidez_pct_YoY,MIN_pct_YoY,ROA_pct_YoY,ROE_pct_YoY,Tasa de interés implícita (TII) cartera de crédito E1 + E2_pct_YoY,Tasa de interés implícita (TII) pasiva_pct_YoY,sofipo,fintech
0,2026-01,0.168547,0.030907,0.187884,2.330104,0.013264,0.106215,0.311773,0.226754,-0.004355,...,-37.14,-59.99,-11.24,-12.39,-158.12,-164.69,-6.79,-11.98,Fincomún,NO
1,2026-02,0.189455,0.030885,0.185861,2.329675,0.013257,0.107628,0.304184,0.227743,-0.004236,...,-38.53,-59.13,-21.2,-10.74,-159.94,-166.74,-6.4,-11.58,Fincomún,NO
2,2026-03,0.193595,0.033345,0.18171,3.452192,0.009659,0.104031,0.337028,0.224523,-0.004991,...,-30.01,-59.86,-10.02,-11.98,-162.79,-169.79,-6.22,-11.14,Fincomún,NO
3,2026-04,0.19361,0.037204,0.17896,2.044809,0.018194,0.113418,0.333336,0.223415,-0.005316,...,62.05,-55.44,-13.35,-11.68,-166.53,-173.47,-5.85,-10.79,Fincomún,NO
4,2026-05,0.196004,0.039524,0.172004,1.71337,0.023068,0.120082,0.296675,0.216663,-0.005292,...,124.49,-53.21,4.8,-14.14,-168.48,-175.07,-5.57,-10.71,Fincomún,NO
5,2026-06,0.187709,0.038191,0.164405,1.698748,0.022482,0.129592,0.567087,0.210121,-0.005589,...,102.22,-49.26,92.4,-15.88,-190.1,-198.39,-5.42,-10.85,Fincomún,NO
6,2026-01,0.128678,0.102854,0.07481,1.151514,0.089321,0.208372,0.830265,0.038131,-0.006147,...,-11.63,7.99,-21.26,130.79,-85.09,-83.28,4.61,-23.97,Total SOFIPOS,NO
7,2026-02,0.139034,0.102319,0.073664,1.144442,0.089405,0.208565,0.814688,0.039993,-0.004195,...,-11.4,7.79,-28.44,147.94,-89.6,-88.92,3.0,-24.36,Total SOFIPOS,NO
8,2026-03,0.141293,0.100287,0.073067,1.092573,0.09179,0.210543,0.81886,0.043225,-0.002031,...,-8.06,8.88,-24.9,153.55,-94.72,-94.68,1.48,-25.95,Total SOFIPOS,NO
9,2026-04,0.143371,0.100428,0.0719,1.067334,0.094092,0.213869,0.791223,0.047191,0.001067,...,-7.17,8.71,-28.17,213.49,-102.71,-102.57,-0.04,-27.2,Total SOFIPOS,NO
10,2026-05,0.141045,0.100749,0.071437,1.039442,0.096926,0.215156,0.788151,0.049125,0.002248,...,-5.28,6.38,-28.63,223.71,-105.86,-105.29,-0.78,-26.99,Total SOFIPOS,NO
11,2026-06,0.143195,0.102665,0.0713,1.036645,0.099036,0.214724,0.756369,0.052068,0.0036,...,-3.56,2.9,-26.78,248.71,-109.66,-108.33,-2.04,-27.54,Total SOFIPOS,NO
12,2026-01,0.119087,0.080205,0.106455,1.397652,0.056834,0.171191,0.636476,0.047536,-0.008501,...,-45.91,1.46,-18.74,190.02,-85.39,-61.82,124.33,-23.09,Fintech,SI
13,2026-02,0.119902,0.078472,0.103455,1.307349,0.05801,0.176206,0.601472,0.048849,-0.004996,...,-22.31,23.68,-27.64,223.46,-91.12,-67.14,122.18,-23.74,Fintech,SI
14,2026-03,0.115345,0.079811,0.098667,1.359427,0.054629,0.176224,0.620117,0.046707,-0.000988,...,-33.61,12.95,-26.31,107.32,-98.15,-80.96,115.12,-24.43,Fintech,SI
15,2026-04,0.117441,0.083281,0.094257,1.35621,0.054462,0.175592,0.601779,0.046597,0.000856,...,-37.87,4.44,-20.87,85.84,-101.63,-86.4,104.98,-25.19,Fintech,SI
16,2026-05,0.114667,0.082312,0.091201,1.316476,0.055527,0.175461,0.546722,0.046944,0.002609,...,-38.38,-2.17,-31.51,72.13,-105.19,-90.29,93.99,-24.57,Fintech,SI
17,2026-06,0.118488,0.082616,0.089349,1.261171,0.060871,0.178136,0.54131,0.047849,0.00337,...,-34.99,-8.16,-33.45,70.41,-107.1,-93.08,81.22,-24.3,Fintech,SI

In [26]:
df_indf_fintech_6m_pivot = df_indf_fintech_6m.pivot(index='sofipo', columns='periodo', values='IMOR cartera de crédito').reset_index()
cols_periodo = df_indf_fintech_6m_pivot.columns.drop('sofipo')

df_indf_fintech_6m_pivot[cols_periodo] =  (df_indf_fintech_6m_pivot[cols_periodo] * 100).round(2)

df_indf_fintech_6m_pivot

periodo,sofipo,2026-01,2026-02,2026-03,2026-04,2026-05,2026-06
0,Fincomún,1.326403,1.325719,0.965908,1.819428,2.306771,2.248188
1,Fintech,5.683447,5.800988,5.462891,5.446155,5.552739,6.087086
2,Total SOFIPOS,8.93207,8.940538,9.178986,9.409218,9.692629,9.903619

In [8]:
vars_bench = ['IMOR cartera de crédito', 
              'IMORA cartera de crédito',
              'ICOR cartera de crédito',
              'EPRC / Cartera de crédito']