In [37]:
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots
import pandas as pd
import numpy as np
import pickle
import os

In [2]:
with open('dict_sofipos_sector.pkl', 'rb') as archivo:
    dict_sofipos = pickle.load(archivo)

In [5]:
dict_sofipos['fintech'].keys()

dict_keys(['Inf_cartera', 'Inf_cartera_E1E2', 'Inf_cartera_E3', 'EPRC', 'Capt_trad', 'Prest_bank', 'CC', 'CG', 'Res_acum', 'Res_ejer', 'Ing_int', 'Ing_int_E1E2', 'Ing_int_E3', 'Ind_financieros', 'Castigos'])

In [11]:
df_indf_fintech = dict_sofipos['fintech']['Inf_cartera']
df_pasivos_fintech = dict_sofipos['fintech']['Capt_trad']

In [21]:
df_pasivos_fintech

,periodo,Pasivo,Captación tradicional,Cuenta global de captación sin movimientos,Depósitos a plazo,Depósitos de exigibilidad inmediata,Títulos de crédito emitidos,Pasivo_i_b100,Pasivo_pct_YoY,Captación tradicional_i_b100,...,Depósitos de exigibilidad inmediata_i_b100,Depósitos de exigibilidad inmediata_pct_YoY,Títulos de crédito emitidos_i_b100,Títulos de crédito emitidos_pct_YoY,Cuenta global de captación sin movimientos_w,Depósitos a plazo_w,Depósitos de exigibilidad inmediata_w,Títulos de crédito emitidos_w,sofipo,fintech
0,2017-01,1586574358.75,1139103143.26,9852483.45,811696710.76,317553949.05,0.0,74.01,NaN,55.98,...,99.76,NaN,NaN,NaN,0.86,71.26,27.88,0.0,Fincomún,NO
1,2017-02,1554934580.94,1112289973.59,9862551.15,792782448.72,309644973.72,0.0,72.53,NaN,54.67,...,97.28,NaN,NaN,NaN,0.89,71.27,27.84,0.0,Fincomún,NO
2,2017-03,1592278624.33,1092798569.46,9677002.0,778936430.46,304185137.0,0.0,74.27,NaN,53.71,...,95.56,NaN,NaN,NaN,0.89,71.28,27.84,0.0,Fincomún,NO
3,2017-04,1583691204.9,1112649225.33,9677002.0,807424673.67,295547549.66,0.0,73.87,NaN,54.68,...,92.85,NaN,NaN,NaN,0.87,72.57,26.56,0.0,Fincomún,NO
4,2017-05,1568917634.89,954605690.73,8895159.0,663814745.21,281895786.52,0.0,73.18,NaN,46.92,...,88.56,NaN,NaN,NaN,0.93,69.54,29.53,0.0,Fincomún,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
793,2026-02,133019219890.600006,127762063760.599991,0.0,32529547910.279999,95232515850.320007,0.0,924.16,6.16,34334.51,...,27636.35,54.93,0,NaN,0.0,25.46,74.54,0.0,Fintech,SI
794,2026-03,130129102676.859985,126108820539.539993,0.0,31568007236.390003,94540813303.149994,0.0,904.08,-0.44,33890.22,...,27435.62,50.36,0,NaN,0.0,25.03,74.97,0.0,Fintech,SI
795,2026-04,126840470503.26001,122765545194.949997,0.0,31035692407.07,91729852787.87999,0.0,881.23,-7.73,32991.75,...,26619.88,43.15,0,NaN,0.0,25.28,74.72,0.0,Fintech,SI
796,2026-05,128646037979.009995,121829435519.100006,0.0,30249021646.590004,91580413872.51001,0.0,893.78,-11.46,32740.19,...,26576.52,34.14,0,NaN,0.0,24.83,75.17,0.0,Fintech,SI
797,2026-06,126393723689.619995,119572362431.750015,0.0,28784299935.259998,90788062496.490005,0.0,878.13,-14.36,32133.62,...,26346.58,29.26,0,NaN,0.0,24.07,75.93,0.0,Fintech,SI

In [24]:
df = pd.merge(left=df_indf_fintech[['periodo', 'Activo', 'sofipo']], right=df_pasivos_fintech[['periodo', 'Pasivo', 'sofipo']], on=['sofipo', 'periodo'], how='left')

In [25]:
df

     periodo               Activo    sofipo               Pasivo
0    2017-01        1950504224.27  Fincomún        1586574358.75
1    2017-02        1917085119.89  Fincomún        1554934580.94
2    2017-03        1959355525.16  Fincomún        1592278624.33
3    2017-04        1953094960.86  Fincomún         1583691204.9
4    2017-05        1940859470.61  Fincomún        1568917634.89
..       ...                  ...       ...                  ...
793  2026-02  149253839126.350006   Fintech  133019219890.600006
794  2026-03  146556951810.820007   Fintech  130129102676.859985
795  2026-04  143428769621.709991   Fintech   126840470503.26001
796  2026-05  145233688021.320038   Fintech  128646037979.009995
797  2026-06  143156587631.859985   Fintech  126393723689.619995

[798 rows x 4 columns]

In [26]:
df['Activo'] = df['Activo']/1000000
df['Pasivo'] = df['Pasivo']/1000000
df['periodo'] = pd.to_datetime(df['periodo'], format='%Y-%m')

In [ ]:
v_periodo = df[df['sofipo'] == 'Fincomún']['periodo']
v_act_finco = df[df['sofipo'] == 'Fincomún']['Activo']
v_pasv_finco = df[df['sofipo'] == 'Fincomún']['Pasivo']

fig = go.Figure()

fig.add_trace(go.Bar(
    x=v_periodo,
    y=v_act_finco,
    name="Activo"
))

fig.add_trace(go.Bar(
    x=v_periodo,
    y=v_pasv_finco,
    name="Pasivo"
))

fig.update_layout(
    barmode="group",  # "group" para barras lado a lado, "stack" para apiladas
    title="Comparación de dos series de tiempo",
    xaxis_title="Fecha",
    yaxis_title="Valor",
    xaxis=dict(tickformat="%b %Y"),
    legend_title="Series",
    template="plotly_white"
)

fig.show()

In [35]:
df_pasivo = df_pasivos_fintech[['periodo', 'Pasivo', 'Captación tradicional', 'sofipo']]
df_pasivo['periodo'] = pd.to_datetime(df_pasivo['periodo'], format='%Y-%m')
df_pasivo = df_pasivo[df_pasivo['periodo'] >= '2024-01-01']

df_pasivo['Pasivo'] = df_pasivo['Pasivo']/1000000
df_pasivo['Captación tradicional'] = df_pasivo['Captación tradicional']/1000000

In [41]:
v_periodo = df_pasivo[df_pasivo['sofipo'] == 'Fincomún']['periodo']
v_captacion_finco = df_pasivo[df_pasivo['sofipo'] == 'Fincomún']['Captación tradicional']
v_pasv_finco = df_pasivo[df_pasivo['sofipo'] == 'Fincomún']['Pasivo']
v_ind = (v_pasv_finco/v_captacion_finco)*100

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(
    go.Bar(
        x=v_periodo,
        y=v_captacion_finco,
        name=f"Captación Tradicional ({v_captacion_finco.iloc[-1]:,.1f})"
    ),
    secondary_y=False
)

fig.add_trace(
    go.Bar(
        x=v_periodo,
        y=v_pasv_finco,
        name=f"Pasivo ({v_pasv_finco.iloc[-1]:,.1f})"
    ),
    secondary_y=False
)

fig.add_trace(
    go.Scatter(
        x=v_periodo,
        y=v_ind,
        name=f"Pasivo / Captación ({v_ind.iloc[-1]:.1f}%)",
        mode="lines+markers",
        line=dict(color="black", width=2)
    ),
    secondary_y=True
)

fig.update_layout(
    barmode="group",
    title="Captación/Pasivo - Fincomún",
    xaxis_title="Fecha",
    legend=dict(
        x=0.01,
        y=0.99,
        xanchor="left",
        yanchor="top",
        bgcolor="rgba(255,255,255,0.6)",
        bordercolor="rgba(0,0,0,0.2)",
        borderwidth=1
    ),
    template="plotly_white"
)

fig.update_xaxes(tickformat="%b %Y")
fig.update_yaxes(title_text="Monto en MDP ($)", secondary_y=False)
fig.update_yaxes(title_text="Pasivo / Captación (%)", secondary_y=True)

fig.show()

In [42]:
df_pasivo['sofipo'].unique()

array(['Fincomún', 'Tamazula', 'Libertad', 'Sofiexpress', 'Crediclub',
       'Total SOFIPOS', 'Fintech'], dtype=object)

In [ ]:
v_periodo = df_pasivo[df_pasivo['sofipo'] == 'Total SOFIPOS']['periodo']
v_captacion_finco = df_pasivo[df_pasivo['sofipo'] == 'Total SOFIPOS']['Captación tradicional']
v_pasv_finco = df_pasivo[df_pasivo['sofipo'] == 'Total SOFIPOS']['Pasivo']
v_ind = (v_pasv_finco/v_captacion_finco)*100

fig = make_subplots(specs=[[{"secondary_y": True}]])

fig.add_trace(
    go.Bar(
        x=v_periodo,
        y=v_captacion_finco,
        name=f"Captación Tradicional ({v_captacion_finco.iloc[-1]:,.1f})"
    ),
    secondary_y=False
)

fig.add_trace(
    go.Bar(
        x=v_periodo,
        y=v_pasv_finco,
        name=f"Pasivo ({v_pasv_finco.iloc[-1]:,.1f})"
    ),
    secondary_y=False
)

fig.add_trace(
    go.Scatter(
        x=v_periodo,
        y=v_ind,
        name=f"Pasivo / Captación ({v_ind.iloc[-1]:.1f}%)",
        mode="lines+markers",
        line=dict(color="black", width=2)
    ),
    secondary_y=True
)

fig.update_layout(
    barmode="group",
    title="Captación/Pasivo - Total SOFIPOS",
    xaxis_title="Fecha",
    legend=dict(
        x=0.01,
        y=0.99,
        xanchor="left",
        yanchor="top",
        bgcolor="rgba(255,255,255,0.6)",
        bordercolor="rgba(0,0,0,0.2)",
        borderwidth=1
    ),
    template="plotly_white"
)

fig.update_xaxes(tickformat="%b %Y")
fig.update_yaxes(title_text="Monto en MDP ($)", secondary_y=False)
fig.update_yaxes(title_text="Pasivo / Captación (%)", secondary_y=True)

fig.show()

In [12]:
df_indf_fintech_s = df_indf_fintech[df_indf_fintech['sofipo'].isin(sele_sofipos)]
df_indf_fintech_s['periodo'] = pd.to_datetime(df_indf_fintech_s['periodo'], format='%Y-%m')

In [13]:
fecha_max = df_indf_fintech_s['periodo'].max()
fecha_limite = fecha_max - pd.DateOffset(months=6)

In [25]:
df_indf_fintech_6m = df_indf_fintech_s[df_indf_fintech_s['periodo'] > fecha_limite].reset_index(drop = True)
df_indf_fintech_6m['periodo'] = df_indf_fintech_6m['periodo'].dt.strftime('%Y-%m')

In [18]:
df_indf_fintech_6m

,periodo,Capital contable / Activo,EPRC / Cartera de crédito,GAP / Activo,ICOR cartera de crédito,IMOR cartera de crédito,IMORA cartera de crédito,Liquidez,MIN,ROA,...,IMOR cartera de crédito_pct_YoY,IMORA cartera de crédito_pct_YoY,Liquidez_pct_YoY,MIN_pct_YoY,ROA_pct_YoY,ROE_pct_YoY,Tasa de interés implícita (TII) cartera de crédito E1 + E2_pct_YoY,Tasa de interés implícita (TII) pasiva_pct_YoY,sofipo,fintech
0,2026-01,0.168547,0.030907,0.187884,2.330104,0.013264,0.106215,0.311773,0.226754,-0.004355,...,-37.14,-59.99,-11.24,-12.39,-158.12,-164.69,-6.79,-11.98,Fincomún,NO
1,2026-02,0.189455,0.030885,0.185861,2.329675,0.013257,0.107628,0.304184,0.227743,-0.004236,...,-38.53,-59.13,-21.2,-10.74,-159.94,-166.74,-6.4,-11.58,Fincomún,NO
2,2026-03,0.193595,0.033345,0.18171,3.452192,0.009659,0.104031,0.337028,0.224523,-0.004991,...,-30.01,-59.86,-10.02,-11.98,-162.79,-169.79,-6.22,-11.14,Fincomún,NO
3,2026-04,0.19361,0.037204,0.17896,2.044809,0.018194,0.113418,0.333336,0.223415,-0.005316,...,62.05,-55.44,-13.35,-11.68,-166.53,-173.47,-5.85,-10.79,Fincomún,NO
4,2026-05,0.196004,0.039524,0.172004,1.71337,0.023068,0.120082,0.296675,0.216663,-0.005292,...,124.49,-53.21,4.8,-14.14,-168.48,-175.07,-5.57,-10.71,Fincomún,NO
5,2026-06,0.187709,0.038191,0.164405,1.698748,0.022482,0.129592,0.567087,0.210121,-0.005589,...,102.22,-49.26,92.4,-15.88,-190.1,-198.39,-5.42,-10.85,Fincomún,NO
6,2026-01,0.128678,0.102854,0.07481,1.151514,0.089321,0.208372,0.830265,0.038131,-0.006147,...,-11.63,7.99,-21.26,130.79,-85.09,-83.28,4.61,-23.97,Total SOFIPOS,NO
7,2026-02,0.139034,0.102319,0.073664,1.144442,0.089405,0.208565,0.814688,0.039993,-0.004195,...,-11.4,7.79,-28.44,147.94,-89.6,-88.92,3.0,-24.36,Total SOFIPOS,NO
8,2026-03,0.141293,0.100287,0.073067,1.092573,0.09179,0.210543,0.81886,0.043225,-0.002031,...,-8.06,8.88,-24.9,153.55,-94.72,-94.68,1.48,-25.95,Total SOFIPOS,NO
9,2026-04,0.143371,0.100428,0.0719,1.067334,0.094092,0.213869,0.791223,0.047191,0.001067,...,-7.17,8.71,-28.17,213.49,-102.71,-102.57,-0.04,-27.2,Total SOFIPOS,NO
10,2026-05,0.141045,0.100749,0.071437,1.039442,0.096926,0.215156,0.788151,0.049125,0.002248,...,-5.28,6.38,-28.63,223.71,-105.86,-105.29,-0.78,-26.99,Total SOFIPOS,NO
11,2026-06,0.143195,0.102665,0.0713,1.036645,0.099036,0.214724,0.756369,0.052068,0.0036,...,-3.56,2.9,-26.78,248.71,-109.66,-108.33,-2.04,-27.54,Total SOFIPOS,NO
12,2026-01,0.119087,0.080205,0.106455,1.397652,0.056834,0.171191,0.636476,0.047536,-0.008501,...,-45.91,1.46,-18.74,190.02,-85.39,-61.82,124.33,-23.09,Fintech,SI
13,2026-02,0.119902,0.078472,0.103455,1.307349,0.05801,0.176206,0.601472,0.048849,-0.004996,...,-22.31,23.68,-27.64,223.46,-91.12,-67.14,122.18,-23.74,Fintech,SI
14,2026-03,0.115345,0.079811,0.098667,1.359427,0.054629,0.176224,0.620117,0.046707,-0.000988,...,-33.61,12.95,-26.31,107.32,-98.15,-80.96,115.12,-24.43,Fintech,SI
15,2026-04,0.117441,0.083281,0.094257,1.35621,0.054462,0.175592,0.601779,0.046597,0.000856,...,-37.87,4.44,-20.87,85.84,-101.63,-86.4,104.98,-25.19,Fintech,SI
16,2026-05,0.114667,0.082312,0.091201,1.316476,0.055527,0.175461,0.546722,0.046944,0.002609,...,-38.38,-2.17,-31.51,72.13,-105.19,-90.29,93.99,-24.57,Fintech,SI
17,2026-06,0.118488,0.082616,0.089349,1.261171,0.060871,0.178136,0.54131,0.047849,0.00337,...,-34.99,-8.16,-33.45,70.41,-107.1,-93.08,81.22,-24.3,Fintech,SI

In [26]:
df_indf_fintech_6m_pivot = df_indf_fintech_6m.pivot(index='sofipo', columns='periodo', values='IMOR cartera de crédito').reset_index()
cols_periodo = df_indf_fintech_6m_pivot.columns.drop('sofipo')

df_indf_fintech_6m_pivot[cols_periodo] =  (df_indf_fintech_6m_pivot[cols_periodo] * 100).round(2)

df_indf_fintech_6m_pivot

periodo,sofipo,2026-01,2026-02,2026-03,2026-04,2026-05,2026-06
0,Fincomún,1.326403,1.325719,0.965908,1.819428,2.306771,2.248188
1,Fintech,5.683447,5.800988,5.462891,5.446155,5.552739,6.087086
2,Total SOFIPOS,8.93207,8.940538,9.178986,9.409218,9.692629,9.903619

In [8]:
vars_bench = ['IMOR cartera de crédito', 
              'IMORA cartera de crédito',
              'ICOR cartera de crédito',
              'EPRC / Cartera de crédito']