In [1]:
import pandas as pd
import numpy as np
import os

Catalogo de SOFIPOS

In [24]:
dir_sofipos = r'C:\Users\lrebollar.e\OneDrive - fincomun.com.mx\Documentos\GitHub\Dashboard Sofipos - Fincomún\cat_instituciones_27.csv'
df_sofipos = pd.read_csv(dir_sofipos, encoding='latin1')
df_sofipos = df_sofipos[['entidad', 'nombre_entidad']]

Nomenclatura de los datos

In [25]:
dir_dicc = r'C:\Users\lrebollar.e\OneDrive - fincomun.com.mx\Documentos\GitHub\Dashboard Sofipos - Fincomún\cat_conceptos_27.csv'
df_dicc = pd.read_csv(dir_dicc, encoding='latin1')

df_dicc_s = df_dicc[['idconcepto', 'descripcion', 'nivel']]

Base global SOFIPOs

In [43]:
dir_df = r'C:\Users\lrebollar.e\OneDrive - fincomun.com.mx\Documentos\GitHub\Dashboard Sofipos - Fincomún\sh_datos_csv_27\sh_datos_27.csv'
df = pd.read_csv(dir_df)

# Se agregan identificadores de variables
df = pd.merge(left=df, right=df_dicc_s, on ='idconcepto', how='left')

# Se agregan nombres de las SOFIPOS
df = pd.merge(left=df, right=df_sofipos, on ='entidad', how='left')

df = df[['nivel',
         'idconcepto',
         'descripcion',
         'entidad',
         'nombre_entidad',
         'periodo',
         'valor'
         ]]

df['periodo'] = pd.to_datetime(df['periodo'].astype(str), format='%Y%m').dt.to_period('M')

In [44]:
df_finco = df[df['nombre_entidad'] == 'Fincomún']

#### Cartera de crédito

In [48]:
var_cartera = [
    27100008, # Cartera
    27100009, # C. Comerciales
    27100010, # C. Consumo
    27100011  # C. Vivienda
]

df_finco_cartera = df_finco[df_finco['idconcepto'].isin(var_cartera)]

df_finco_cartera_pivot = df_finco_cartera.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_cartera_pivot

descripcion,periodo,Cartera de crédito,Créditos comerciales,Créditos consumo,Créditos vivienda
0,2017-01,1.565634e+09,5.871918e+08,9.697392e+08,8702884.15
1,2017-02,1.568731e+09,5.839989e+08,9.767433e+08,7988843.94
2,2017-03,1.564749e+09,5.838287e+08,9.729097e+08,8010179.28
3,2017-04,1.562953e+09,5.870026e+08,9.680117e+08,7939031.38
4,2017-05,1.496393e+09,5.891290e+08,8.992679e+08,7995802.16
...,...,...,...,...,...
109,2026-02,3.098939e+09,1.064554e+09,2.025497e+09,8887645.92
110,2026-03,3.105877e+09,1.081691e+09,2.015325e+09,8861508.38
111,2026-04,3.055323e+09,1.033908e+09,2.012579e+09,8835218.37
112,2026-05,2.971019e+09,9.841491e+08,1.978061e+09,8808774.99
113,2026-06,2.918610e+09,9.541600e+08,1.955673e+09,8777055.78

## Cuentas de Activo
#### Estimación preventiva para riesgos crediticios

In [ ]:
var_riesgo = [
    27100012, # Cartera
    27100013, # C. Comerciales
    27100014, # C. Consumo
    27100015,  # C. Vivienda
    27100148
]

df_finco_riesgo = df_finco[df_finco['idconcepto'].isin(var_riesgo)]

df_finco_riesgo_pivot = df_finco_riesgo.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_riesgo_pivot['compro'] = df_finco_riesgo_pivot

descripcion,periodo,Créditos comerciales,Créditos consumo,Créditos vivienda,Estimaciones preventivas para riesgos crediticios adicional,Estimación preventiva para riesgos crediticios
0,2017-01,-28006707.59,-48735391.01,-30460.10,0.00,-7.677256e+07
1,2017-02,-59989175.66,-20585868.78,-30460.10,-449596.66,-8.105510e+07
2,2017-03,-29258689.21,-61719732.60,-61483.73,-949572.05,-9.198948e+07
3,2017-04,-31145935.31,-67747081.74,-126775.88,-1503678.39,-1.005235e+08
4,2017-05,-32836367.58,-22983554.46,-435886.48,-1503719.24,-5.775953e+07
...,...,...,...,...,...,...
109,2026-02,-43889048.94,-51790424.06,-31106.76,0.00,-9.571058e+07
110,2026-03,-47396664.19,-56137824.99,-31015.28,0.00,-1.035655e+08
111,2026-04,-53308569.24,-60330217.49,-30923.26,0.00,-1.136697e+08
112,2026-05,-56480725.55,-60913587.43,-30830.71,0.00,-1.174251e+08
113,2026-06,-48459677.22,-62974399.58,-30719.70,0.00,-1.114648e+08

#### Cartera de crédito con riesgo de crédito (E1 + E2)

In [50]:
var_riesgo_E1E2 = [
    27100037, # Cartera
    27100038, # C. Comerciales
    27100039, # C. Consumo
    27100040  # C. Vivienda
]

df_finco_riesgo_E1E2 = df_finco[df_finco['idconcepto'].isin(var_riesgo_E1E2)]

df_finco_riesgo_E1E2_pivot = df_finco_riesgo_E1E2.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_riesgo_E1E2_pivot

descripcion,periodo,Cartera de crédito con riesgo de crédito (E1 + E2),Créditos comerciales (E1 + E2),Créditos consumo (E1 + E2),Créditos vivienda (E1 + E2)
0,2017-01,1.514005e+09,5.670827e+08,9.382190e+08,8702884.15
1,2017-02,1.457730e+09,5.629033e+08,8.868374e+08,7988843.94
2,2017-03,1.385238e+09,5.626675e+08,8.145608e+08,8010179.28
3,2017-04,1.322780e+09,5.661382e+08,7.487031e+08,7939031.38
4,2017-05,1.276515e+09,5.666006e+08,7.019184e+08,7995802.16
...,...,...,...,...,...
109,2026-02,3.057855e+09,1.041874e+09,2.007094e+09,8887645.92
110,2026-03,3.075878e+09,1.065574e+09,2.001442e+09,8861508.38
111,2026-04,2.999733e+09,9.975646e+08,1.993333e+09,8835218.37
112,2026-05,2.902484e+09,9.356226e+08,1.958053e+09,8808774.99
113,2026-06,2.852994e+09,9.102468e+08,1.933971e+09,8777055.78

#### Cartera de crédito con riesgo de crédito etapa 3

In [51]:
var_riesgo_E3 = [
    27100004, # Cartera
    27100005, # C. Comerciales
    27100006, # C. Consumo
    27100007  # C. Vivienda
]

df_finco_riesgo_E3 = df_finco[df_finco['idconcepto'].isin(var_riesgo_E3)]

df_finco_riesgo_E3_pivot = df_finco_riesgo_E3.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_riesgo_E3_pivot

descripcion,periodo,Cartera de crédito con riesgo de crédito etapa 3,Créditos comerciales,Créditos consumo,Créditos vivienda
0,2017-01,5.162938e+07,20109109.81,3.152027e+07,0.0
1,2017-02,1.110014e+08,21095578.87,8.990585e+07,0.0
2,2017-03,1.795101e+08,21161169.29,1.583489e+08,0.0
3,2017-04,2.401729e+08,20864361.52,2.193086e+08,0.0
4,2017-05,2.198779e+08,22528419.72,1.973495e+08,0.0
...,...,...,...,...,...
109,2026-02,4.108323e+07,22679663.51,1.840356e+07,0.0
110,2026-03,2.999993e+07,16116042.27,1.388389e+07,0.0
111,2026-04,5.558939e+07,36343897.22,1.924549e+07,0.0
112,2026-05,6.853461e+07,48526501.69,2.000811e+07,0.0
113,2026-06,6.561585e+07,43913159.24,2.170269e+07,0.0

## Cuentas de Pasivo
#### Captación Tradicional

In [ ]:
var_captacion = [
    27100044, # Captación tradicional NVL 1
    27100028, # Depósitos de exigibilidad inmediata
    27100158, # Títulos de crédito emitidos
    27100083  # Cuenta global de captación sin movimientos
]

df_finco_captacion = df_finco[df_finco['idconcepto'].isin(var_captacion)]

df_finco_captacion_pivot = df_finco_captacion.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_captacion_pivot

descripcion,periodo,Captación tradicional,Cuenta global de captación sin movimientos,Depósitos de exigibilidad inmediata,Títulos de crédito emitidos
0,2017-01,1.139103e+09,9852483.45,3.175539e+08,0.0
1,2017-02,1.112290e+09,9862551.15,3.096450e+08,0.0
2,2017-03,1.092799e+09,9677002.00,3.041851e+08,0.0
3,2017-04,1.112649e+09,9677002.00,2.955475e+08,0.0
4,2017-05,9.546057e+08,8895159.00,2.818958e+08,0.0
...,...,...,...,...,...
109,2026-02,2.670465e+09,0.00,4.028388e+08,0.0
110,2026-03,2.685383e+09,0.00,4.264111e+08,0.0
111,2026-04,2.733525e+09,0.00,4.412211e+08,0.0
112,2026-05,2.753379e+09,0.00,4.461400e+08,0.0
113,2026-06,2.790952e+09,0.00,4.561080e+08,0.0

#### Préstamos bancarios y de otros organismos

In [57]:
var_prestamosb = [
    27100030, # Préstamos bancarios y de otros organismos NVL 1
    27100159, # De corto plazo
    27100160, # De largo plazo
]

df_finco_prestamosb = df_finco[df_finco['idconcepto'].isin(var_prestamosb)]

df_finco_prestamosb_pivot = df_finco_prestamosb.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_prestamosb_pivot

descripcion,periodo,De corto plazo,De largo plazo,Préstamos bancarios y de otros organismos
0,2017-01,3.371658e+08,3.364951e+07,3.708154e+08
1,2017-02,3.280619e+08,2.762043e+07,3.556823e+08
2,2017-03,4.037504e+08,1.222223e+07,4.159726e+08
3,2017-04,3.744022e+08,1.013890e+07,3.845411e+08
4,2017-05,3.970401e+08,1.373889e+08,5.344290e+08
...,...,...,...,...
109,2026-02,5.187492e+08,0.000000e+00,5.187492e+08
110,2026-03,5.060171e+08,0.000000e+00,5.060171e+08
111,2026-04,4.276299e+08,0.000000e+00,4.276299e+08
112,2026-05,4.160676e+08,0.000000e+00,4.160676e+08
113,2026-06,5.177467e+08,0.000000e+00,5.177467e+08

## Cuentas de Capital
#### Capital Contable

In [58]:
var_CC = [
    27100002, # Capital contable NVL 1
    27100084, # Capital contribuido
    27100086, # Capital ganado
]

df_finco_CC = df_finco[df_finco['idconcepto'].isin(var_CC)]

df_finco_CC_pivot = df_finco_CC.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_CC_pivot

descripcion  periodo  Capital contable  Capital contribuido  Capital ganado
0            2017-01      3.639299e+08          395370000.0    -31440134.48
1            2017-02      3.621505e+08          395370000.0    -33219461.05
2            2017-03      3.670769e+08          395370000.0    -28293099.17
3            2017-04      3.694038e+08          395370000.0    -25966244.04
4            2017-05      3.719418e+08          395370000.0    -23428164.28
..               ...               ...                  ...             ...
109          2026-02      7.596465e+08          693246237.0     66400237.21
110          2026-03      7.819511e+08          715363091.0     66588007.10
111          2026-04      7.820083e+08          715363091.0     66645190.06
112          2026-05      7.821097e+08          715363091.0     66746566.02
113          2026-06      7.764811e+08          715363091.0     61117987.23

[114 rows x 4 columns]

##### Capital Ganado

In [ ]:
var_CG = [
    27100086, # Capital ganado NVL 2
    27100165, # Reservas de capital
    27100166, # Incremento por actualización de reservas de capital 
    27100211, # Resultados acumulados
    27100212  # Otros resultados integrales
]

df_finco_CG = df_finco[df_finco['idconcepto'].isin(var_CG)]

df_finco_CG_pivot = df_finco_CG.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_CG_pivot

descripcion,periodo,Capital ganado,Incremento por actualización de reservas de capital,Reservas de capital,Resultados acumulados
0,2017-01,-31440134.48,121323.27,10042195.75,-41863594.66
1,2017-02,-33219461.05,121323.27,10042195.75,-43565402.78
2,2017-03,-28293099.17,121323.27,10042195.75,-38628064.50
3,2017-04,-25966244.04,121323.27,10042195.75,-36285167.39
4,2017-05,-23428164.28,121323.27,10042195.75,-33591683.30
...,...,...,...,...,...
109,2026-02,66400237.21,121323.27,37384752.01,28894161.93
110,2026-03,66588007.10,121323.27,37384752.01,29081931.82
111,2026-04,66645190.06,121323.27,37384752.01,29139114.78
112,2026-05,66746566.02,121323.27,37384752.01,29240490.74
113,2026-06,61117987.23,121323.27,37384752.01,23611911.95

##### Resultados acumulados

In [61]:
var_racum = [
    27100211, # Resultados acumulados NVL3
    27100167, # Reservas de capital
    27100168, # Incremento por actualización de reservas de capital 
    27100198, # Resultados acumulados
]

df_finco_racum = df_finco[df_finco['idconcepto'].isin(var_racum)]

df_finco_racum_pivot = df_finco_racum.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_racum_pivot

descripcion,periodo,Incremento por actualización del resultado de ejercicios anteriores,Resultado Neto,Resultado de ejercicios anteriores,Resultados acumulados
0,2017-01,0.0,-2265387.71,-39598206.95,-41863594.66
1,2017-02,0.0,-3967195.83,-39598206.95,-43565402.78
2,2017-03,0.0,970142.45,-39598206.95,-38628064.50
3,2017-04,0.0,3313039.56,-39598206.95,-36285167.39
4,2017-05,0.0,6006523.65,-39598206.95,-33591683.30
...,...,...,...,...,...
109,2026-02,0.0,1118802.39,27775359.54,28894161.93
110,2026-03,0.0,1306572.28,27775359.54,29081931.82
111,2026-04,0.0,1363755.24,27775359.54,29139114.78
112,2026-05,0.0,1465131.20,27775359.54,29240490.74
113,2026-06,0.0,-4163447.59,27775359.54,23611911.95

## Estado de Resultados Integral
#### Resultados del Ejercicio

In [66]:
var_RE = [
    27100041, # Ingresos por intereses NVL 1
    27100023, # Gastos por intereses
    27100043, # Margen financiero
    27100017, # Margen financiero ajustado por riesgos crediticios
    27100042, # Resultado de la operación
    27100101, # Resultado antes de impuestos a la utilidad
    27100093, # Resultado por operaciones continuas
    27100003, # Resultado neto
    27100225, # Otros resultados integrales
    27100226, # Participación en ORI de otras entidades
    27100227, # RESULTADO INTEGRAL
]

df_finco_RE = df_finco[df_finco['idconcepto'].isin(var_RE)]

df_finco_RE_pivot = df_finco_RE.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_RE_pivot

descripcion,periodo,Gastos por intereses,Ingresos por intereses,Margen financiero,Margen financiero ajustado por riesgos crediticios,Otros resultados integrales,Participación en ORI de otras entidades,RESULTADO INTEGRAL,Resultado antes de impuestos a la utilidad,Resultado de la operación,Resultado neto,Resultado por operaciones continuas
0,2017-01,9.080436e+06,7.688469e+07,6.780426e+07,4.957505e+07,0.0,NaN,-2265387.71,-2265387.71,-2265387.71,-2265387.71,-2265387.71
1,2017-02,1.699563e+07,1.529927e+08,1.359971e+08,1.009804e+08,0.0,NaN,-3967195.83,-3967195.83,-3967195.83,-3967195.83,-3967195.83
2,2017-03,2.660341e+07,2.339766e+08,2.073732e+08,1.530597e+08,0.0,NaN,970142.45,970142.45,970142.45,970142.45,970142.45
3,2017-04,3.555927e+07,3.098969e+08,2.743376e+08,1.965539e+08,0.0,NaN,3313039.56,3313039.56,3313039.56,3313039.56,3313039.56
4,2017-05,4.532664e+07,3.872166e+08,3.418899e+08,2.415528e+08,0.0,NaN,6006523.65,6006523.65,6006523.65,6006523.65,6006523.65
...,...,...,...,...,...,...,...,...,...,...,...,...
109,2026-02,4.221948e+07,2.292813e+08,1.870618e+08,1.151069e+08,0.0,0.0,1118802.39,1118802.39,1986083.07,1118802.39,1118802.39
110,2026-03,6.394977e+07,3.524051e+08,2.884553e+08,1.729901e+08,0.0,0.0,1306572.28,1306572.28,2176074.26,1306572.28,1306572.28
111,2026-04,8.503027e+07,4.737973e+08,3.887670e+08,2.347279e+08,0.0,0.0,1363755.24,1363755.24,2358911.22,1363755.24,1363755.24
112,2026-05,1.061628e+08,5.919383e+08,4.857755e+08,2.834210e+08,0.0,0.0,1465131.20,1465131.20,2622505.04,1465131.20,1465131.20
113,2026-06,1.262049e+08,7.050095e+08,5.788046e+08,3.260433e+08,0.0,0.0,-4163447.59,-4163447.59,-2671491.50,-4163447.59,-4163447.59

#### Ingresos por intereses

In [62]:
var_ingint = [
    27100041, # Ingresos por intereses NVL 1
    27100031, # Intereses de efectivo y equivalentes de efectivo
    27100184, # Intereses y rendimientos a favor provenientes de inversiones en instrumentos financieros
    27100185, # Intereses y rendimientos a favor en operaciones de reporto
    27100033, # Intereses de cartera de crédito con riesgo de crédito (E1 + E2)
    27100140, # Intereses de cartera de crédito con riesgo de crédito etapa 3
    27100144, # Ingresos por cartera de crédito valuada a valor razonable
    27100213, # Intereses por derechos de cobro adquiridos
    27100186, # Comisiones por el otorgamiento del crédito
    27100214, # Efecto por renegociación de cartera de crédito
    27100215, # Primas por colocación de deuda
    27100216, # Dividendos de instrumentos financieros que califican como instrumentos financieros de capital
    27100187, # Utilidad por valorización
    27100217  # Incremento por actualización de ingresos por intereses 
]

df_finco_ingint = df_finco[df_finco['idconcepto'].isin(var_ingint)]

df_finco_ingint_pivot = df_finco_ingint.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_ingint_pivot

descripcion,periodo,Comisiones por el otorgamiento del crédito,Dividendos de instrumentos financieros que califican como instrumentos financieros de capital,Efecto por renegociación de cartera de crédito,Incremento por actualización de ingresos por intereses,Ingresos por cartera de crédito valuada a valor razonable,Ingresos por intereses,Intereses de cartera de crédito con riesgo de crédito (E1 + E2),Intereses de cartera de crédito con riesgo de crédito etapa 3,Intereses de efectivo y equivalentes de efectivo,Intereses por derechos de cobro adquiridos,Intereses y rendimientos a favor en operaciones de reporto,Intereses y rendimientos a favor provenientes de inversiones en instrumentos financieros,Primas por colocación de deuda,Utilidad por valorización
0,2017-01,1823588.26,0.0,NaN,0.0,NaN,7.688469e+07,7.305241e+07,1480473.93,35994.59,NaN,0.00,492226.13,0.0,0.0
1,2017-02,3498086.93,0.0,NaN,0.0,NaN,1.529927e+08,1.441074e+08,4506503.77,78807.24,NaN,0.00,801960.33,0.0,0.0
2,2017-03,5518407.27,0.0,NaN,0.0,NaN,2.339766e+08,2.193809e+08,7835485.07,117559.19,NaN,0.00,1124283.39,0.0,0.0
3,2017-04,7198049.68,0.0,NaN,0.0,NaN,3.098969e+08,2.900984e+08,10794256.42,172529.83,NaN,0.00,1633692.68,0.0,0.0
4,2017-05,9137245.56,0.0,NaN,0.0,NaN,3.872166e+08,3.615583e+08,14073565.28,234772.75,NaN,0.00,2212693.81,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,2026-02,8080291.82,0.0,0.0,0.0,0.0,2.292813e+08,2.183984e+08,312667.54,369040.59,0.0,2120841.53,0.00,0.0,0.0
110,2026-03,12471183.46,0.0,0.0,0.0,0.0,3.524051e+08,3.350440e+08,790847.39,557120.46,0.0,3542001.60,0.00,0.0,0.0
111,2026-04,16351895.16,0.0,0.0,0.0,0.0,4.737973e+08,4.499450e+08,1808542.18,732950.01,0.0,4958880.50,0.00,0.0,0.0
112,2026-05,20082676.34,0.0,0.0,0.0,0.0,5.919383e+08,5.623228e+08,2082267.97,904986.70,0.0,6545554.12,0.00,0.0,0.0
113,2026-06,23742480.71,0.0,0.0,0.0,0.0,7.050095e+08,6.702205e+08,2218171.38,1063987.75,0.0,7764425.39,0.00,0.0,0.0

##### Intereses de cartera de crédito con riesgo de crédito (E1 + E2)

In [63]:
var_intE1E2 = [
    27100033, # Intereses de cartera de crédito con riesgo de crédito (E1 + E2) NVL 2
    27100034, # Créditos comerciales (E1 + E2)
    27100035, # Créditos consumo (E1 + E2)
    27100036, # Créditos vivienda (E1 + E2)
]

df_finco_intE1E2 = df_finco[df_finco['idconcepto'].isin(var_intE1E2)]

df_finco_intE1E2_pivot = df_finco_intE1E2.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_intE1E2_pivot

descripcion,periodo,Créditos comerciales (E1 + E2),Créditos consumo (E1 + E2),Créditos vivienda (E1 + E2),Intereses de cartera de crédito con riesgo de crédito (E1 + E2)
0,2017-01,4.863273e+07,2.441868e+07,1004.01,7.305241e+07
1,2017-02,9.161833e+07,5.162683e+07,862215.54,1.441074e+08
2,2017-03,1.393261e+08,7.784440e+07,2210347.95,2.193809e+08
3,2017-04,1.855997e+08,1.010066e+08,3492014.79,2.900984e+08
4,2017-05,2.334458e+08,1.233219e+08,4790536.38,3.615583e+08
...,...,...,...,...,...
109,2026-02,1.271914e+08,9.110379e+07,103248.86,2.183984e+08
110,2026-03,1.950101e+08,1.398792e+08,154646.26,3.350440e+08
111,2026-04,2.615404e+08,1.881987e+08,205891.22,4.499450e+08
112,2026-05,3.258772e+08,2.361886e+08,256982.85,5.623228e+08
113,2026-06,3.893920e+08,2.805511e+08,277350.62,6.702205e+08

##### Intereses de cartera de crédito con riesgo de crédito etapa 3

In [64]:
var_intE3 = [
    27100140, # Intereses de cartera de crédito con riesgo de crédito etapa 3 NVL 2
    27100141, # Créditos comerciales 
    27100142, # Créditos consumo
    27100143, # Créditos vivienda
]

df_finco_intE3 = df_finco[df_finco['idconcepto'].isin(var_intE3)]

df_finco_intE3_pivot = df_finco_intE3.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_intE3_pivot

descripcion,periodo,Créditos comerciales,Créditos consumo,Créditos vivienda,Intereses de cartera de crédito con riesgo de crédito etapa 3
0,2017-01,1462042.06,18431.87,0.0,1480473.93
1,2017-02,3663526.83,842976.94,0.0,4506503.77
2,2017-03,6066830.88,1768654.19,0.0,7835485.07
3,2017-04,8212390.63,2581865.79,0.0,10794256.42
4,2017-05,10627798.24,3445767.04,0.0,14073565.28
...,...,...,...,...,...
109,2026-02,104944.97,207722.57,0.0,312667.54
110,2026-03,479767.05,311080.34,0.0,790847.39
111,2026-04,1350719.27,457822.91,0.0,1808542.18
112,2026-05,1489258.82,593009.15,0.0,2082267.97
113,2026-06,1610004.86,608166.52,0.0,2218171.38

##### Ingresos por cartera de crédito valuada a valor razonable

In [65]:
var_valr = [
    27100144, # Ingresos por cartera de crédito valuada a valor razonable NVL 2
    27100145, # Créditos comerciales 
    27100146, # Créditos consumo
    27100147, # Créditos vivienda
]

df_finco_valr = df_finco[df_finco['idconcepto'].isin(var_valr)]

df_finco_valr_pivot = df_finco_valr.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_valr_pivot

descripcion,periodo,Créditos comerciales,Créditos consumo,Créditos vivienda,Ingresos por cartera de crédito valuada a valor razonable
0,2026-01,0.0,0.0,0.0,0.0
1,2026-02,0.0,0.0,0.0,0.0
2,2026-03,0.0,0.0,0.0,0.0
3,2026-04,0.0,0.0,0.0,0.0
4,2026-05,0.0,0.0,0.0,0.0
5,2026-06,0.0,0.0,0.0,0.0

## Indicadores Financieros

In [67]:
var_ind = [
    27200001,	# ROA
    27200002,	# ROE
    27200113,	# Liquidez
    27200004,	# MIN
    27200114,	# GAP / Activo
    27200021,	# Capital contable / Activo
    27200005,	# IMOR cartera de crédito
    27200009,	# IMORA cartera de crédito
    27200013,	# ICOR cartera de crédito
    27200017,	# EPRC / Cartera de crédito
    27200115,	# Tasa de interés implícita (TII) cartera de crédito E1 + E2
    27200119,	#Tasa de interés implícita (TII) pasiva
]

df_finco_ind = df_finco[df_finco['idconcepto'].isin(var_ind)]

df_finco_ind_pivot = df_finco_ind.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

df_finco_ind_pivot

descripcion,periodo,Capital contable / Activo,EPRC / Cartera de crédito,GAP / Activo,ICOR cartera de crédito,IMOR cartera de crédito,IMORA cartera de crédito,Liquidez,MIN,ROA,ROE,Tasa de interés implícita (TII) cartera de crédito E1 + E2,Tasa de interés implícita (TII) pasiva
0,2017-01,0.186582,0.049036,0.355171,1.486994,0.032977,0.114983,0.165411,0.384651,0.003079,0.019155,0.611616,0.063787
1,2017-02,0.188907,0.051669,0.350760,0.730217,0.070759,0.215801,0.165411,0.382957,0.003650,0.022405,0.606046,0.064102
2,2017-03,0.187346,0.058789,0.340681,0.512447,0.114721,0.276981,0.160796,0.380103,0.006205,0.037592,0.603103,0.065235
3,2017-04,0.189138,0.064316,0.331708,0.418546,0.153666,0.314223,0.147902,0.374750,0.007214,0.042989,0.600913,0.066208
4,2017-05,0.191638,0.038599,0.322446,0.262689,0.146939,0.347814,0.233457,0.369939,0.006044,0.035499,0.599529,0.067367
...,...,...,...,...,...,...,...,...,...,...,...,...,...
109,2026-02,0.189455,0.030885,0.185861,2.329675,0.013257,0.107628,0.304184,0.227743,-0.004236,-0.022766,0.447455,0.081852
110,2026-03,0.193595,0.033345,0.181710,3.452192,0.009659,0.104031,0.337028,0.224523,-0.004991,-0.026872,0.446611,0.081420
111,2026-04,0.193610,0.037204,0.178960,2.044809,0.018194,0.113418,0.333336,0.223415,-0.005316,-0.028620,0.447053,0.080947
112,2026-05,0.196004,0.039524,0.172004,1.713370,0.023068,0.120082,0.296675,0.216663,-0.005292,-0.028474,0.446516,0.080287
113,2026-06,0.187709,0.038191,0.164405,1.698748,0.022482,0.129592,0.567087,0.210121,-0.005589,-0.030140,0.445702,0.079409

## Castigos, quitas y condonaciones

In [ ]:
var_castigo = [
    27200085,	# Castigos, quitas y condonaciones (Suma 12 meses)
    27200086,	# Créditos comerciales
    27200087,	# Créditos consumo
    27200088,	# Créditos vivienda
]

df_finco_castigo = df_finco[df_finco['idconcepto'].isin(var_castigo)]

df_finco_castigo_pivot = df_finco_castigo.pivot(
    index='periodo',
    columns='descripcion',
    values='valor'
).reset_index()

# Transformaciones internas
vars = df_finco_castigo_pivot.columns.to_list()[1:]

for var in vars:

    base = df_finco_castigo_pivot[df_finco_castigo_pivot['periodo'] == '2019-07'][var].iat[0]
    df_finco_castigo_pivot[f'{var}_i_b100'] = round((df_finco_castigo_pivot[var]/base)*100, 2)
    df_finco_castigo_pivot[f'{var}_w'] = round((df_finco_castigo_pivot[var]/df_finco_castigo_pivot['Castigos, quitas y condonaciones (Suma 12 meses)'])*100, 2)

In [82]:
df_finco_castigo_pivot

descripcion,periodo,"Castigos, quitas y condonaciones (Suma 12 meses)",Créditos comerciales,Créditos consumo,Créditos vivienda,"Castigos, quitas y condonaciones (Suma 12 meses)_i_b100",Créditos comerciales_i_b100,Créditos consumo_i_b100,Créditos vivienda_i_b100,Créditos comerciales_w,Créditos consumo_w,Créditos vivienda_w
0,2017-01,1.450726e+08,8.879315e+07,5.627943e+07,0.00,18.69,47.01,9.59,0.00,61.21,38.79,0.00
1,2017-02,2.901452e+08,1.775863e+08,1.125589e+08,0.00,37.38,94.01,19.17,0.00,61.21,38.79,0.00
2,2017-03,3.511612e+08,2.142258e+08,1.369162e+08,19148.52,45.24,113.41,23.32,9.56,61.00,38.99,0.01
3,2017-04,3.659244e+08,2.159203e+08,1.499347e+08,69343.85,47.14,114.31,25.54,34.64,59.01,40.97,0.02
4,2017-05,4.608929e+08,2.177297e+08,2.429746e+08,188601.56,59.38,115.26,41.39,94.21,47.24,52.72,0.04
...,...,...,...,...,...,...,...,...,...,...,...,...
109,2026-02,3.277218e+08,1.507165e+08,1.769952e+08,10044.58,42.22,79.79,30.15,5.02,45.99,54.01,0.00
110,2026-03,3.271393e+08,1.550151e+08,1.721142e+08,9927.76,42.15,82.06,29.32,4.96,47.39,52.61,0.00
111,2026-04,3.281590e+08,1.553090e+08,1.728402e+08,9806.11,42.28,82.22,29.44,4.90,47.33,52.67,0.00
112,2026-05,3.275643e+08,1.649543e+08,1.626003e+08,9686.49,42.20,87.33,27.70,4.84,50.36,49.64,0.00
113,2026-06,3.591565e+08,1.858061e+08,1.733409e+08,9562.02,46.27,98.36,29.53,4.78,51.73,48.26,0.00

0      18.69
1      37.38
2      45.24
3      47.14
4      59.38
       ...
109    42.22
110    42.15
111    42.28
112    42.20
113    46.27
Name: Castigos, quitas y condonaciones (Suma 12 meses)_i_b100, Length: 114, dtype: float64